class_name Shop
extends Node3D
## A shop counter in the world: something you walk up to, carrying a
## [ShopDefinition] of what it sells.
##
## ## It owns no rules
##
## Pressing the key does not open a shop UI from here, because there is no shop UI
## yet and building one blind would be group 25's job with nothing to test against.
## What the counter does instead:
##
##   * reports itself to the interaction probe, so it gets a prompt like any other
##     world object — which is what makes it *reachable*, the first row of the
##     economy acceptance criteria;
##   * publishes [signal opened], so whatever UI comes later has one obvious place
##     to hang off;
##   * holds the definition, so the stock is content and not a switch statement.
##
## The buy and sell rules are [EconomyService]'s. See that file for why they are not
## methods here.

## Emitted when the player interacts with the counter. A shop UI listens here.
signal opened(shop: Shop, actor: Node)
## Emitted after a successful trade at this counter, so a UI can rebuild its rows
## without listening to the whole [EventBus].
signal traded(kind: StringName, item_id: StringName, quantity: int, total: int)

## Which counter this is. Null is legal but makes the shop inert; the prompt says so
## rather than pretending otherwise.
@export var shop: ShopDefinition

## The interactable component. Created in [method _ready] when a scene did not
## provide one, so the counter works whether it was placed in a hand-built scene or
## generated by the world builder.
@export var interactable: ShopInteractable


func _ready() -> void:
	if shop == null:
		Log.warn("Shop", "%s has no ShopDefinition and cannot trade" % name)
	if interactable == null:
		interactable = ShopInteractable.new()
		interactable.name = "ShopInteractable"
		# The inherited default is "Interact", which would read "Interact General
		# Store" — accurate, and useless, since the player cannot tell from the
		# prompt that a *trade* is on offer. Set here rather than exported so a
		# counter placed in a hand-built scene gets it too.
		interactable.prompt_text = "Trade at"
		# Added before anything reads it: an autoload-free node written to before it
		# enters the tree logs an error every boot (see `AGENTS.md`, "Two
		# Godot-specific traps").
		add_child(interactable)
	interactable.shop = self
	interactable.opened.connect(_on_opened)


## The [EconomyService] this counter trades through, found by group.
##
## Group rather than a reference because the shop is built by the world generator
## deep inside a scene tree, and threading a service into it would make the world
## depend on the economy — the same inversion [SoilTileInteractable] documents for
## the farm service.
func economy() -> EconomyService:
	return EconomyService.find()


## Buys through this counter, so the definition and the service cannot be mixed up.
##
## Publishes [signal traded] on success. On refusal it stays silent: the failure
## has already been published on [signal EventBus.trade_failed] with its reason,
## and a `traded` that fires for a refused sale is exactly the ambiguous event
## `AGENTS.md` forbids.
func buy(item_id: StringName, quantity: int = 1) -> Dictionary:
	var service := economy()
	if service == null:
		return _no_service(item_id, quantity)
	var result := service.buy(shop, item_id, quantity)
	if bool(result["ok"]):
		traded.emit(
			&"buy", item_id, int(result["quantity"]), int(result["total"])
		)
	return result


## Sells through this counter.
func sell(item_id: StringName, quantity: int = 1) -> Dictionary:
	var service := economy()
	if service == null:
		return _no_service(item_id, quantity)
	var result := service.sell(shop, item_id, quantity)
	if bool(result["ok"]):
		traded.emit(
			&"sell", item_id, int(result["quantity"]), int(result["total"])
		)
	return result


## What the player is carrying that this counter would pay for, as
## `{item_id: total_price}` for the whole stack.
##
## A convenience for a future UI, and the reason [method sell] takes a quantity
## rather than requiring it. Derived from the bag on every call, never cached: a
## cached list goes stale the moment the player sells a parsnip, and a shop screen
## that still offers one is worse than no shop screen.
##
## Totals across qualities, because a price is per item and the shop pays the same
## rate whatever the crop happens to be. A shop that valued quality separately
## would need [method Inventory.summary] to keep the quality component, which it
## does — the caller can go straight there if that ever changes.
func sellable_totals() -> Dictionary:
	var owner := PlayerStateService.find()
	var service := economy()
	var out: Dictionary = {}
	if owner == null or owner.inventory == null or shop == null or service == null:
		return out
	var totals := owner.inventory.summary()
	for key: String in totals.keys():
		var id := StringName(key.get_slice(":", 0))
		var unit := service.pays_for(shop, id)
		if unit <= 0:
			continue
		out[id] = unit * int(totals[key])
	return out


func _no_service(item_id: StringName, quantity: int) -> Dictionary:
	return {
		"ok": false, "reason": "no_economy_service", "item_id": item_id,
		"quantity": quantity, "total": 0,
	}


func _on_opened(actor: Node) -> void:
	opened.emit(self, actor)
	# Also on the bus, so a screen can listen in one place rather than hunting the
	# tree for whichever counter happens to be nearby. Without this the counter's
	# interaction was invisible: `opened` fired, and a signal nobody subscribes to
	# is indistinguishable from a broken game to the player pressing E.
	EventBus.shop_opened.emit(self)